const statuses = {
	INIT: 'INIT',
	// INPROGRESS: 'INPROGRESS',
	SUCCESS: 'SUCCESS',
	FAILURE: 'FAILURE',
	REQUEST: 'REQUEST',
	
	ERROR: 'ERROR',
	CAPTHCAREQUIRED: 'CAPTHCAREQUIRED',
};

export default statuses;
